telegram_token: "1669141248:AAEhP4EZTfjpu-Zu2NhiQvrGlSr4J1L2tho"
# ONLY IF YOU USING DATA FORMATTING FUNCTION, NOTE for developer: important or test fail
#time_outdata: "02/01/2006 15:04:05" 
#template_path: "template.tmpl" # ONLY IF YOU USING TEMPLATE
#time_zone: "Europe/Moscow" # ONLY IF YOU USING TEMPLATE
#split_msg_byte: 4000
#send_only: true # use bot only to send messages.
